### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by designstorming** [HipsterBrown/package-search#1]
Error text: "Package is invalid. Details: 'Could not load icon 'icons/icon19.png' for browser action.'."

**Comment by HipsterBrown** [comment]
@designstorming This should be fixed in the latest patch. https://chrome.google.com/webstore/detail/resource-finder/edlpcnogjoailkfgcnemkleoemcggdji?hl=en-US&gl=US&authuser=1

Thanks for filing the issue.
